### PR TITLE
VINS Fusion support for Ubuntu 20.04 with Ceres Solver 2.0.0

### PR DESCRIPTION
**Pull request by stevenf7**
Updated OpenCV and C++ requirements to support Ubuntu 20.04, ROS Noetic, and Ceres Solver v2.0.0

### CODE REVIEW

**Comment by MadlyFX** [comment]
Throws this when using the Realsense D435I config:

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) /home/andy/opencv/modules/video/src/lkpyramid.cpp:1257: error: (-215:Assertion failed) maxLevel >= 0 && winSize.width > 2 && winSize.height > 2 in function 'calc'

Aborted (core dumped)

```

**Comment by 2B-people** [comment]
Amazing!  Worked on Ubuntu 20.04, ROS Noetic,OpenCV4

**Comment by Buttosaii** [comment]
I am using Ubuntu 20.04 and Noetic too, how can I use this branch instead of the main branch? Thanks!

**Comment by stevenf7** [comment]
> I am using Ubuntu 20.04 and Noetic too, how can I use this branch instead of the main branch? Thanks!

Nice, you can go to my repo and clone that directly

**Comment by Buttosaii** [comment]
> 

WOW! Thank you so much! I managed to build it without any errors. Can i check with you if ur repo performs exactly the same as the main repo, or is there any difference I should take note of?

**Comment by stevenf7** [comment]
> > 
> 
> WOW! Thank you so much! I managed to build it without any errors. Can I check with you if ur repo performs exactly the same as the main repo, or is there any difference I should take note of?

It should work exactly the same as the original repo.

**Comment by Buttosaii** [comment]
Hi @stevenf7, can I seek your advice regarding converting 18.04 repo to 20.04. I recently bought a new laptop which is facing a lot of issues when dual booting 18.04. However, I wouldn't want to put the laptop to waste, thus my next alternative would be to dual boot it with 20.04, and run VINS-Fusion & GVINS on 20.04. However, due to my lack of experience, is it possible for you to guide me through the steps? Also, is it possible for me to contact you personally? 

Your help would be greatly appreciated! Thank you!

**Comment by stevenf7** [comment]
Hi Buttosaii, 
Thank you for reaching out and apologize for the late rely, I have been busy with school. I don't have much advice other than looking at the dependencies of each package to see what needs to be updates, possibly modify the C++ version in the cmake file, and check the error when you are compiling it. Perhaps you may also verify it has already been done via the issues: https://github.com/HKUST-Aerial-Robotics/GVINS/issues and maybe check out this PR: https://github.com/HKUST-Aerial-Robotics/GVINS/pull/13/commits
Best of luck! 
Steven

**Comment by jaku-jaku** [comment]
@stevenf7  Thanks for the work! 
(Additional Tip: Install Ceres 1.14.0, will not work with Ceres 2.x.x)
