### ISSUE TITLE
catkin_make完之后拿Euroc数据集测试，但是报错。

### ISSUE THREAD

**Issue by GGshmily** [HKUST-Aerial-Robotics/VINS-Fusion#194]
数据集是:MH_02_easy.bag
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.5-dev) /home/jimlee/LHG/opencv/modules/core/src/matrix_wrap.cpp:423: error: (-215:Assertion failed) i < 0 in function 'size'

已放弃 (核心已转储)

**Comment by chongjeelee** [comment]
i have the same problem ,do you solved it ?

**Comment by Rick-Weng** [comment]
你是不是之前的编译出现了警告？[ WARN] [1665062148.295888966]:  fix extrinsic param 。我用了ulimit -s  102400扩充栈内存后就变成新问题了。

**Comment by GopiRajuMatta** [comment]
Facing the same problem. Any update on this?

**Comment by GGshmily** [comment]
> 你是不是之前的编译出现了警告？[ WARN] [1665062148.295888966]: fix extrinsic param 。我用了ulimit -s 102400扩充栈内存后就变成新问题了。

我解决了，是我的电脑里有两个版本的opencv，我拿opencv4.5编译的，但是运行的时候会使用libopencv3的库，所以会崩溃

**Comment by GGshmily** [comment]
maybe is the contradictory of opencv4.5 and libopencv3. I build with opencv4.5，but VINS automaticly used libopencv3. You can  change libopencv3 to libopencv4.5 or build VINS with opencv3.

**Comment by GopiRajuMatta** [comment]
Thank you for the response. Once I built it using opencv4, how can I make sure that it uses opencv4? Can you please help me with this.
